
version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.18
commands:
  front-build:
    parameters:
      stage:
        default: 'dev'
        type: string
    steps:
      - run: npm run build-<< parameters.stage >>
  front-deploy:
    parameters:
      stage:
        default: 'DEV'
        type: string
    steps:
      - run: aws s3 sync dist/frontend-gzip/ s3://${S3_BUCKET_<< parameters.stage >>}/ --delete --exact-timestamps --content-encoding gzip;
jobs:
  install-and-lint:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      # - run:
      #     name: Lint
      #     command: npm run lint
      - persist_to_workspace:
          root: .
          paths:
            - .
  semantic-release:
    docker:
      - image: 'circleci/node:16'
    steps:
      - attach_workspace:
          at: .
      - run: mkdir -p ~/.ssh
      - run: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Semantic release
          command: npx semantic-release
  build-deploy-dev:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - front-build:
          stage: 'dev'
      - run: 
          name: Install AWS CLI
          command: sudo apt-get update && sudo apt-get install awscli
      - front-deploy:
          stage: 'DEV'
  build-deploy-demo:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - front-build:
          stage: 'demo'
      - run: 
          name: Install AWS CLI
          command: sudo apt-get update && sudo apt-get install awscli
      - front-deploy:
          stage: 'DEMO'
  build-deploy-prod:
    working_directory: ~/frontend
    docker:
      - image: circleci/node:16
    steps:
      - attach_workspace:
          at: .
      - front-build:
          stage: 'prod'
      - run: 
          name: Install AWS CLI
          command: sudo apt-get update && sudo apt-get install awscli
      - front-deploy:
          stage: 'PROD'

filter_workflow-jobs: &filter_workflow-jobs
  branches:
    only:
      - main

workflows:
  build_and_deploy:
    jobs:
      - install-and-lint:
          filters:
            branches:
              only:
                - development
                - main
            # tags:
            #   only: /v[0-9]+(\.[0-9]+)+/
      - build-deploy-dev:
          context: aws-secrets
          name: deploy-dev
          requires:
            - install-and-lint
          filters:
            branches:
              only:
                - development
      # - build-deploy-demo:
      #     context: aws-secrets
      #     name: deploy-demo
      #     requires:
      #       - install-and-lint
      #     filters:
      #       <<: *filter_workflow-jobs
      - hold-deploy-prod:
          type: approval
          requires:
            - install-and-lint
          filters:
            <<: *filter_workflow-jobs
      - build-deploy-prod:
          context: aws-secrets
          name: deploy-prod
          filters:
            <<: *filter_workflow-jobs
          requires:
            - hold-deploy-prod
      - semantic-release:
          context: semantic-release
          name: semantic-release
          requires:
            - hold-deploy-prod
          filters:
            <<: *filter_workflow-jobs
