
version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package-lock.json" }}
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build
          command: |
            if [ $CIRCLE_BRANCH = 'development' ]; then
              npm run build-dev
            fi
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    working_directory: ~/repo
    docker:
      - image: innovatorjapan/awscli:latest
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy
          command: |
            if [ $CIRCLE_BRANCH = 'development' ]; then
              aws s3 sync dist/frontend-gzip/ s3://buychain-front-dev/ --delete --exact-timestamps --content-encoding gzip;
            fi
workflows:
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - development
      - deploy:
          context: aws-secrets
          requires:
            - build
          filters:
            branches:
              only:
                - development
