export * from './companies.service';
import { CompaniesService } from './companies.service';
export * from './crm.service';
import { CrmService } from './crm.service';
export * from './facilities.service';
import { FacilitiesService } from './facilities.service';
export * from './groups.service';
import { GroupsService } from './groups.service';
export * from './labels.service';
import { LabelsService } from './labels.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './rateTables.service';
import { RateTablesService } from './rateTables.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './temporaryCompanies.service';
import { TemporaryCompaniesService } from './temporaryCompanies.service';
export * from './transactions.service';
import { TransactionsService } from './transactions.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [CompaniesService, CrmService, FacilitiesService, GroupsService, LabelsService, ProductsService, RateTablesService, StatusService, TemporaryCompaniesService, TransactionsService, UsersService];
