/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CompanyPrivateDataAccountingPractices { 
    inventoryMgmtSystem?: CompanyPrivateDataAccountingPractices.InventoryMgmtSystemEnum;
    fiscalYearStart?: CompanyPrivateDataAccountingPractices.FiscalYearStartEnum;
    revenueRecognitionMethod?: CompanyPrivateDataAccountingPractices.RevenueRecognitionMethodEnum;
}
export namespace CompanyPrivateDataAccountingPractices {
    export type InventoryMgmtSystemEnum = 'FIFO' | 'AVG_COST';
    export const InventoryMgmtSystemEnum = {
        FIFO: 'FIFO' as InventoryMgmtSystemEnum,
        AVGCOST: 'AVG_COST' as InventoryMgmtSystemEnum
    };
    export type FiscalYearStartEnum = 'JAN' | 'FEB' | 'MAR' | 'APR' | 'MAY' | 'JUN' | 'JUL' | 'AUG' | 'SEPT' | 'OCT' | 'NOV' | 'DEC';
    export const FiscalYearStartEnum = {
        JAN: 'JAN' as FiscalYearStartEnum,
        FEB: 'FEB' as FiscalYearStartEnum,
        MAR: 'MAR' as FiscalYearStartEnum,
        APR: 'APR' as FiscalYearStartEnum,
        MAY: 'MAY' as FiscalYearStartEnum,
        JUN: 'JUN' as FiscalYearStartEnum,
        JUL: 'JUL' as FiscalYearStartEnum,
        AUG: 'AUG' as FiscalYearStartEnum,
        SEPT: 'SEPT' as FiscalYearStartEnum,
        OCT: 'OCT' as FiscalYearStartEnum,
        NOV: 'NOV' as FiscalYearStartEnum,
        DEC: 'DEC' as FiscalYearStartEnum
    };
    export type RevenueRecognitionMethodEnum = 'BOOKING' | 'SHIPPED' | 'CUST_RECEIVED' | 'INVOICED' | 'PAID';
    export const RevenueRecognitionMethodEnum = {
        BOOKING: 'BOOKING' as RevenueRecognitionMethodEnum,
        SHIPPED: 'SHIPPED' as RevenueRecognitionMethodEnum,
        CUSTRECEIVED: 'CUST_RECEIVED' as RevenueRecognitionMethodEnum,
        INVOICED: 'INVOICED' as RevenueRecognitionMethodEnum,
        PAID: 'PAID' as RevenueRecognitionMethodEnum
    };
}
