/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Company } from './company';
import { CompanyAccountingPractices } from './companyAccountingPractices';
import { CompanyContract } from './companyContract';
import { CompanyFeatures } from './companyFeatures';
import { CompanyPrivacySettings } from './companyPrivacySettings';
import { CompanySalesPractices } from './companySalesPractices';


export interface CompanyDetails { 
    readonly companyState?: CompanyDetails.CompanyStateEnum;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    readonly id?: string;
    /**
     * Unique.
     */
    readonly name?: string;
    /**
     * Website.
     */
    website?: string;
    streetAddress?: string;
    city?: string;
    state?: string;
    country?: string;
    zipCode?: string;
    /**
     * Null is allowed.
     */
    logoUrl?: string;
    accountingPractices?: CompanyAccountingPractices;
    privacySettings?: CompanyPrivacySettings;
    salesPractices?: CompanySalesPractices;
    contract?: CompanyContract;
    features?: CompanyFeatures;
}
export namespace CompanyDetails {
    export type CompanyStateEnum = 'ACTIVE' | 'ARCHIVED';
    export const CompanyStateEnum = {
        ACTIVE: 'ACTIVE' as CompanyStateEnum,
        ARCHIVED: 'ARCHIVED' as CompanyStateEnum
    };
}
