/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CompanyMemberAccountState { 
    accountState: CompanyMemberAccountState.AccountStateEnum;
}
export namespace CompanyMemberAccountState {
    export type AccountStateEnum = 'APPROVED' | 'HOLD' | 'UPDATE_REQUIRED';
    export const AccountStateEnum = {
        APPROVED: 'APPROVED' as AccountStateEnum,
        HOLD: 'HOLD' as AccountStateEnum,
        UPDATEREQUIRED: 'UPDATE_REQUIRED' as AccountStateEnum
    };
}
