/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface CompanySalesPractices { 
    selectionCriteria?: CompanySalesPractices.SelectionCriteriaEnum;
}
export namespace CompanySalesPractices {
    export type SelectionCriteriaEnum = 'LOW_COST_BASIS' | 'HIGH_COST_BASIS' | 'FIFO_PURCHASE_DATE' | 'LIFO_PURCHASE_DATE';
    export const SelectionCriteriaEnum = {
        LOWCOSTBASIS: 'LOW_COST_BASIS' as SelectionCriteriaEnum,
        HIGHCOSTBASIS: 'HIGH_COST_BASIS' as SelectionCriteriaEnum,
        FIFOPURCHASEDATE: 'FIFO_PURCHASE_DATE' as SelectionCriteriaEnum,
        LIFOPURCHASEDATE: 'LIFO_PURCHASE_DATE' as SelectionCriteriaEnum
    };
}
