/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CrmAccountLocationBaseGeolocation } from './crmAccountLocationBaseGeolocation';


export interface CrmAccountLocationBase { 
    readonly id?: string;
    /**
     * Hex, ref Facilities. Unique within company. Null is allowed.
     */
    link?: string;
    /**
     * Null is allowed.
     */
    shortName: string;
    /**
     * Null is allowed.
     */
    streetAddress?: string;
    /**
     * Null is allowed.
     */
    city?: string;
    /**
     * Null is allowed.
     */
    state?: string;
    /**
     * Null is allowed.
     */
    country?: string;
    /**
     * Null is allowed.
     */
    zipCode?: string;
    /**
     * Null is allowed.
     */
    loadingHours?: string;
    /**
     * Null is allowed.
     */
    loadingNotes?: string;
    /**
     * Null is allowed.
     */
    receivingHours?: string;
    /**
     * Null is allowed.
     */
    receivingNotes?: string;
    /**
     * Null is allowed.
     */
    careOf?: string;
    /**
     * Null is allowed.
     */
    logoUrl?: string;
    geolocation?: CrmAccountLocationBaseGeolocation;
    /**
     * Hex, ref Crm-Accounts.
     */
    readonly crmAccountId?: string;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    archived?: boolean;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
