/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CrmAccountContactBase } from './crmAccountContactBase';
import { CrmAccountContactSalesInfo } from './crmAccountContactSalesInfo';


export interface CrmAccountContact { 
    readonly id?: string;
    /**
     * Hex, ref Users. Unique within company. Null is allowed.
     */
    link?: string;
    /**
     * Null is allowed.
     */
    username?: string;
    firstName: string;
    lastName: string;
    /**
     * Null is allowed.
     */
    profilePictureUrl?: string;
    /**
     * Null is allowed.
     */
    title?: string;
    /**
     * Calling code. Null is allowed.
     */
    callingCode?: string;
    /**
     * Null is allowed.
     */
    workPhone?: string;
    readonly crmAccountId?: string;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    archived?: boolean;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    salesInfo?: CrmAccountContactSalesInfo;
}
