/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FacilityBase } from './facilityBase';
import { FacilityBaseGeolocation } from './facilityBaseGeolocation';
import { FacilityPersonnel } from './facilityPersonnel';
import { TransportMethod } from './transportMethod';


export interface Facility { 
    readonly id?: string;
    description: string;
    streetAddress: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
    /**
     * Hex, ref Rate-Tables. Null is allowed.
     */
    rateTableId?: string;
    /**
     * Null is allowed.
     */
    generalHours?: string;
    /**
     * Null is allowed.
     */
    loadingHours?: string;
    /**
     * Null is allowed.
     */
    receivingHours?: string;
    /**
     * Null is allowed.
     */
    generalNotes?: string;
    /**
     * Null is allowed.
     */
    loadingNotes?: string;
    /**
     * Null is allowed.
     */
    receivingNotes?: string;
    /**
     * Null is allowed.
     */
    careOf?: string;
    /**
     * Null is allowed.
     */
    logoUrl?: string;
    geolocation?: FacilityBaseGeolocation;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    archived?: boolean;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    /**
     * Unique.
     */
    shortName?: string;
    personnel?: Array<FacilityPersonnel>;
    transportMethods?: Array<TransportMethod>;
}
