/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface FacilityPersonnel { 
    /**
     * Hex, ref Uses.
     */
    userId: string;
    description: string;
    department: FacilityPersonnel.DepartmentEnum;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace FacilityPersonnel {
    export type DepartmentEnum = 'LOADING' | 'RECEIVING';
    export const DepartmentEnum = {
        LOADING: 'LOADING' as DepartmentEnum,
        RECEIVING: 'RECEIVING' as DepartmentEnum
    };
}
