/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.266.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CrmAccountLocationBaseGeolocation } from './crmAccountLocationBaseGeolocation';
import { FacilityBase } from './facilityBase';


export interface FacilityUpdatePayload { 
    readonly id?: string;
    description: string;
    streetAddress: string;
    city: string;
    state: string;
    country: string;
    zipCode: string;
    generalHours?: string;
    generalNotes?: string;
    careOf?: string;
    logoUrl?: string;
    geolocation?: CrmAccountLocationBaseGeolocation;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    readonly archived?: string;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    /**
     * Hex, ref Rate-Tables.
     */
    rateTableId?: string;
    loadingHours?: string;
    receivingHours?: string;
    loadingNotes?: string;
    receivingNotes?: string;
}
