/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FacilityEmbeddedInCrmLocationLinkGeolocation } from './facilityEmbeddedInCrmLocationLinkGeolocation';
import { FacilityPersonnel } from './facilityPersonnel';
import { TransportMethod } from './transportMethod';


export interface FacilityEmbeddedInCrmLocationLink { 
    readonly id?: string;
    shortName?: string;
    description?: string;
    streetAddress?: string;
    city?: string;
    state?: string;
    country?: string;
    zipCode?: string;
    rateTableId?: string;
    generalHours?: string;
    loadingHours?: string;
    receivingHours?: string;
    generalNotes?: string;
    loadingNotes?: string;
    receivingNotes?: string;
    careOf?: string;
    logoUrl?: string;
    geolocation?: FacilityEmbeddedInCrmLocationLinkGeolocation;
    personnel?: Array<FacilityPersonnel>;
    transportMethods?: Array<TransportMethod>;
}
