/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { GroupAccountingInfo } from './groupAccountingInfo';
import { GroupBase } from './groupBase';


export interface Group { 
    readonly id?: string;
    /**
     * Unique within company.
     */
    name: string;
    /**
     * Null is allowed.
     */
    description?: string;
    /**
     * Null is allowed.
     */
    imageUrl?: string;
    /**
     * Hex, ref Groups. Null is allowed.
     */
    parent?: string;
    /**
     * Hex, ref Users. Default Requesting-User.
     */
    manager?: string;
    /**
     * Hex, ref Users. Default Company.accountingPractices.defaultBillToContact.
     */
    accountingContact?: string;
    readonly parentTree?: Array<string>;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    readonly archived?: string;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    accountingInfo?: GroupAccountingInfo;
}
