/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface GroupAccountingInfo { 
    /**
     * Null is allowed.
     */
    EIN?: number;
    /**
     * ISO 4217 currency code.
     */
    currency?: GroupAccountingInfo.CurrencyEnum;
    /**
     * Null is allowed.
     */
    paymentDetails?: string;
    /**
     * Hex, ref Accounts. Default Company.accountingPractices.defaultAccounts.retainedEarnings.
     */
    rEAccountId?: string;
}
export namespace GroupAccountingInfo {
    export type CurrencyEnum = 'USD';
    export const CurrencyEnum = {
        USD: 'USD' as CurrencyEnum
    };
}
