/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LabelBase } from './labelBase';


export interface Label { 
    readonly id?: string;
    name: string;
    description: string;
    /**
     * Hex code.
     */
    color: string;
    labelSet?: Label.LabelSetEnum;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace Label {
    export type LabelSetEnum = 'ACCOUNT_INDUSTRY_TYPE' | 'ACCOUNT_CATEGORY_TAG' | 'ACCOUNT_TAG' | 'CONTACT_ROLE_TAG' | 'CONTACT_TAG' | 'LOCATION_TAG';
    export const LabelSetEnum = {
        ACCOUNTINDUSTRYTYPE: 'ACCOUNT_INDUSTRY_TYPE' as LabelSetEnum,
        ACCOUNTCATEGORYTAG: 'ACCOUNT_CATEGORY_TAG' as LabelSetEnum,
        ACCOUNTTAG: 'ACCOUNT_TAG' as LabelSetEnum,
        CONTACTROLETAG: 'CONTACT_ROLE_TAG' as LabelSetEnum,
        CONTACTTAG: 'CONTACT_TAG' as LabelSetEnum,
        LOCATIONTAG: 'LOCATION_TAG' as LabelSetEnum
    };
}
