/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { OrderOwnerData } from './orderOwnerData';
import { OrderStockData } from './orderStockData';


export interface Order { 
    readonly id?: string;
    readonly state?: Order.StateEnum;
    type: Order.TypeEnum;
    subtype: Order.SubtypeEnum;
    ownerData?: OrderOwnerData;
    stockData?: OrderStockData;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace Order {
    export type StateEnum = 'OPEN' | 'CLOSED';
    export const StateEnum = {
        OPEN: 'OPEN' as StateEnum,
        CLOSED: 'CLOSED' as StateEnum
    };
    export type TypeEnum = 'STOCK';
    export const TypeEnum = {
        STOCK: 'STOCK' as TypeEnum
    };
    export type SubtypeEnum = 'PURCHASE' | 'SALES';
    export const SubtypeEnum = {
        PURCHASE: 'PURCHASE' as SubtypeEnum,
        SALES: 'SALES' as SubtypeEnum
    };
}
