/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductLotProductLog } from './productLotProductLog';


export interface ProductLotProduct { 
    readonly id?: string;
    costBasis?: number;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly purchaseDate?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly custodyDate?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly landedDate?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly soldDate?: Date;
    readonly trackingNumber?: string;
    /**
     * Hex, ref Transactions.
     */
    readonly acquiredTransactionId?: string;
    /**
     * Hex, ref Transactions.
     */
    readonly soldTransactionId?: string;
    readonly log?: Array<ProductLotProductLog>;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
