/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductLog { 
    readonly event?: ProductLog.EventEnum;
    /**
     * Hex, ref Users.
     */
    readonly user?: string;
    readonly data?: any;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace ProductLog {
    export type EventEnum = 'ADD_PRODUCT_LOT' | 'UPDATE_PRODUCT_LOT' | 'UPDATE_PRODUCT_SPEC_LENGTH_UNITS' | 'ALLOCATE_PRODUCT_LOT' | 'SPLIT_PRODUCT_LOT' | 'ROLLBACK_ALLOCATED_PRODUCT_LOT' | 'ARCHIVE_PRODUCT_LOT' | 'CANCEL_PRODUCT' | 'ACQUIRE_PRODUCT_LOT' | 'UPDATE_PRODUCT_LOT_WITH_CHANGE_PENDING' | 'SET_PRODUCT_LOT_STATE_IN_TRANSIT' | 'SET_PRODUCT_LOT_STATE_ON_HAND' | 'SET_PRODUCT_LOT_STATE_CANCELED';
    export const EventEnum = {
        ADDPRODUCTLOT: 'ADD_PRODUCT_LOT' as EventEnum,
        UPDATEPRODUCTLOT: 'UPDATE_PRODUCT_LOT' as EventEnum,
        UPDATEPRODUCTSPECLENGTHUNITS: 'UPDATE_PRODUCT_SPEC_LENGTH_UNITS' as EventEnum,
        ALLOCATEPRODUCTLOT: 'ALLOCATE_PRODUCT_LOT' as EventEnum,
        SPLITPRODUCTLOT: 'SPLIT_PRODUCT_LOT' as EventEnum,
        ROLLBACKALLOCATEDPRODUCTLOT: 'ROLLBACK_ALLOCATED_PRODUCT_LOT' as EventEnum,
        ARCHIVEPRODUCTLOT: 'ARCHIVE_PRODUCT_LOT' as EventEnum,
        CANCELPRODUCT: 'CANCEL_PRODUCT' as EventEnum,
        ACQUIREPRODUCTLOT: 'ACQUIRE_PRODUCT_LOT' as EventEnum,
        UPDATEPRODUCTLOTWITHCHANGEPENDING: 'UPDATE_PRODUCT_LOT_WITH_CHANGE_PENDING' as EventEnum,
        SETPRODUCTLOTSTATEINTRANSIT: 'SET_PRODUCT_LOT_STATE_IN_TRANSIT' as EventEnum,
        SETPRODUCTLOTSTATEONHAND: 'SET_PRODUCT_LOT_STATE_ON_HAND' as EventEnum,
        SETPRODUCTLOTSTATECANCELED: 'SET_PRODUCT_LOT_STATE_CANCELED' as EventEnum
    };
}
