/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductLotSpecDimension } from './productLotSpecDimension';


export interface ProductLotSpec { 
    priceSystem: ProductLotSpec.PriceSystemEnum;
    unitPieceCount: number;
    productGroupName: string;
    productName: string;
    pattern?: string;
    cutType?: string;
    subspecies?: string;
    subGrade?: string;
    seasoningChemical?: string;
    finish?: string;
    mfgProcess?: string;
    rating?: string;
    standard?: string;
    patternWidth?: string;
    classification?: string;
    certification?: string;
    /**
     * Positive.
     */
    depth?: number;
    species?: string;
    width?: ProductLotSpecDimension;
    type?: string;
    seasoning?: string;
    grade?: string;
    thickness?: ProductLotSpecDimension;
    length?: ProductLotSpecDimension;
}
export namespace ProductLotSpec {
    export type PriceSystemEnum = 'USD/M-BOARD-FEET' | 'USD/SQUARE-FEET' | 'USD/LINEAR-FEET';
    export const PriceSystemEnum = {
        MBOARDFEET: 'USD/M-BOARD-FEET' as PriceSystemEnum,
        SQUAREFEET: 'USD/SQUARE-FEET' as PriceSystemEnum,
        LINEARFEET: 'USD/LINEAR-FEET' as PriceSystemEnum
    };
}
