/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductLotSpecDimension { 
    /**
     * Positive.
     */
    value?: number;
    name?: string;
    uom?: ProductLotSpecDimension.UomEnum;
}
export namespace ProductLotSpecDimension {
    export type UomEnum = 'feet' | 'inch';
    export const UomEnum = {
        Feet: 'feet' as UomEnum,
        Inch: 'inch' as UomEnum
    };
}
