/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductLotProductLog { 
    readonly event?: ProductLotProductLog.EventEnum;
    /**
     * Hex, ref Users.
     */
    readonly user?: string;
    readonly data?: any;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace ProductLotProductLog {
    export type EventEnum = 'ADD_PRODUCT' | 'MOVE_PRODUCT' | 'RECALCULATE_PRODUCT_COST_BASIS';
    export const EventEnum = {
        ADDPRODUCT: 'ADD_PRODUCT' as EventEnum,
        MOVEPRODUCT: 'MOVE_PRODUCT' as EventEnum,
        RECALCULATEPRODUCTCOSTBASIS: 'RECALCULATE_PRODUCT_COST_BASIS' as EventEnum
    };
}
