/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductEmbeddedInTransactionTallyUnitDateHistory } from './productEmbeddedInTransactionTallyUnitDateHistory';
import { ProductEmbeddedInTransactionTallyUnitOfflineData } from './productEmbeddedInTransactionTallyUnitOfflineData';
import { ProductEmbeddedInTransactionTallyUnitOnlineData } from './productEmbeddedInTransactionTallyUnitOnlineData';
import { ProductEmbeddedInTransactionTallyUnitPriceHistory } from './productEmbeddedInTransactionTallyUnitPriceHistory';
import { ProductSalesData } from './productSalesData';
import { ProductSpec } from './productSpec';


export interface ProductEmbeddedInTransactionTallyUnit { 
    readonly id?: string;
    readonly mfgFacilityShortName?: string;
    offlineData?: ProductEmbeddedInTransactionTallyUnitOfflineData;
    onlineData?: ProductEmbeddedInTransactionTallyUnitOnlineData;
    salesData?: ProductSalesData;
    spec?: ProductSpec;
    priceHistory?: ProductEmbeddedInTransactionTallyUnitPriceHistory;
    dateHistory?: ProductEmbeddedInTransactionTallyUnitDateHistory;
}
