/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductLotUpdatePayload { 
    salesNotes?: string;
    permission?: ProductLotUpdatePayload.PermissionEnum;
    /**
     * Hex, ref Users.
     */
    ownerId?: string;
}
export namespace ProductLotUpdatePayload {
    export type PermissionEnum = 'PRIVATE' | 'INTERNAL' | 'EXTERNAL';
    export const PermissionEnum = {
        PRIVATE: 'PRIVATE' as PermissionEnum,
        INTERNAL: 'INTERNAL' as PermissionEnum,
        EXTERNAL: 'EXTERNAL' as PermissionEnum
    };
}
