/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ProductLotEmbeddedInTransactionTallyUnitOfflineData { 
    /**
     * Hex, ref Crm-Locations.
     */
    shipFromId?: string;
    shipFromShortName?: string;
}
