/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductSpecDimension } from './productSpecDimension';


export interface ProductSpec { 
    priceSystem: ProductSpec.PriceSystemEnum;
    unitPieceCount: number;
    productGroupName: ProductSpec.ProductGroupNameEnum;
    productName: ProductSpec.ProductNameEnum;
    pattern?: string;
    cutType?: string;
    subspecies?: string;
    subGrade?: string;
    seasoningChemical?: string;
    finish?: string;
    mfgProcess?: string;
    rating?: string;
    standard?: string;
    patternWidth?: string;
    classification?: string;
    certification?: string;
    /**
     * Positive.
     */
    depth?: number;
    species?: string;
    width?: ProductSpecDimension;
    type?: string;
    seasoning?: string;
    grade?: string;
    thickness?: ProductSpecDimension;
    length?: ProductSpecDimension;
    lengthUnits?: any;
}
export namespace ProductSpec {
    export type PriceSystemEnum = 'USD/M-BOARD-FEET' | 'USD/SQUARE-FEET' | 'USD/LINEAR-FEET';
    export const PriceSystemEnum = {
        MBOARDFEET: 'USD/M-BOARD-FEET' as PriceSystemEnum,
        SQUAREFEET: 'USD/SQUARE-FEET' as PriceSystemEnum,
        LINEARFEET: 'USD/LINEAR-FEET' as PriceSystemEnum
    };
    export type ProductGroupNameEnum = 'Lumber' | 'Panel' | 'Engineered';
    export const ProductGroupNameEnum = {
        Lumber: 'Lumber' as ProductGroupNameEnum,
        Panel: 'Panel' as ProductGroupNameEnum,
        Engineered: 'Engineered' as ProductGroupNameEnum
    };
    export type ProductNameEnum = 'Dim' | 'OSB' | 'CP' | 'LVL' | 'Rim Board' | 'Plywood' | 'Veneer' | 'MDO' | 'Glulam';
    export const ProductNameEnum = {
        Dim: 'Dim' as ProductNameEnum,
        OSB: 'OSB' as ProductNameEnum,
        CP: 'CP' as ProductNameEnum,
        LVL: 'LVL' as ProductNameEnum,
        RimBoard: 'Rim Board' as ProductNameEnum,
        Plywood: 'Plywood' as ProductNameEnum,
        Veneer: 'Veneer' as ProductNameEnum,
        MDO: 'MDO' as ProductNameEnum,
        Glulam: 'Glulam' as ProductNameEnum
    };
}
