/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RateTableEntryBase } from './rateTableEntryBase';
import { TransportMethod } from './transportMethod';


export interface RateTableEntry { 
    readonly id?: string;
    cost: number;
    /**
     * Null is allowed.
     */
    destinationDescription?: string;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    /**
     * Positive.
     */
    capacity?: number;
    destinationShortName?: string;
    destinationCity?: string;
    destinationState?: string;
    destinationCountry?: string;
    transportMethod?: TransportMethod;
    uom?: RateTableEntry.UomEnum;
}
export namespace RateTableEntry {
    export type UomEnum = 'BOARD_FEET' | 'SQUARE_FEET' | 'LINEAR_FEET';
    export const UomEnum = {
        BOARDFEET: 'BOARD_FEET' as UomEnum,
        SQUAREFEET: 'SQUARE_FEET' as UomEnum,
        LINEARFEET: 'LINEAR_FEET' as UomEnum
    };
}
