/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionCostDataCostOfGoodBase { 
    readonly id?: string;
    readonly type?: TransactionCostDataCostOfGoodBase.TypeEnum;
    value: number;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
}
export namespace TransactionCostDataCostOfGoodBase {
    export type TypeEnum = 'DUTIES' | 'CUSTOMS' | 'INSURANCE' | 'OCEAN_FREIGHT' | 'HANDLING' | 'BROKERAGE' | 'COMMISSION' | 'OTHER';
    export const TypeEnum = {
        DUTIES: 'DUTIES' as TypeEnum,
        CUSTOMS: 'CUSTOMS' as TypeEnum,
        INSURANCE: 'INSURANCE' as TypeEnum,
        OCEANFREIGHT: 'OCEAN_FREIGHT' as TypeEnum,
        HANDLING: 'HANDLING' as TypeEnum,
        BROKERAGE: 'BROKERAGE' as TypeEnum,
        COMMISSION: 'COMMISSION' as TypeEnum,
        OTHER: 'OTHER' as TypeEnum
    };
}
