/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionTransactionalJournalEntry } from './transactionTransactionalJournalEntry';


export interface TransactionTransactionalJournalEntryPopulated { 
    readonly id?: string;
    user?: any;
    message: string;
    readonly type?: TransactionTransactionalJournalEntryPopulated.TypeEnum;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace TransactionTransactionalJournalEntryPopulated {
    export type TypeEnum = 'MESSAGING' | 'LOG';
    export const TypeEnum = {
        MESSAGING: 'MESSAGING' as TypeEnum,
        LOG: 'LOG' as TypeEnum
    };
}
