/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductLotEmbeddedInTransactionTallyUnit } from './productLotEmbeddedInTransactionTallyUnit';
import { TransactionTallyUnitBase } from './transactionTallyUnitBase';


export interface TransactionTallyUnitPartiallyPopulated { 
    readonly id?: string;
    offer?: number;
    qty?: number;
    readonly updatedAt?: Date;
    readonly createdAt?: Date;
    lineItem?: ProductLotEmbeddedInTransactionTallyUnit;
}
