/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.247.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionCostDataUpdatePayload { 
    shippingCost?: number;
}
