/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionTrackingDataBuyerDataCrmData { 
    /**
     * Hex, ref Crm-Accounts. Required if autofillBackwards is missing.
     */
    buyingCompany?: string;
    /**
     * Hex, ref Crm-Contacts. Required if autofillBackwards is missing.
     */
    buyingUser?: string;
    /**
     * Hex, ref Crm-Locations. Required if autofillBackwards is missing.
     */
    shipTo?: string;
    /**
     * Hex, ref Crm-Contacts. Forbidden if autofillBackwards is present (optional otherwise)
     */
    billToContact?: string;
    /**
     * Hex, ref Crm-Locations. Forbidden if autofillBackwards is present (optional otherwise)
     */
    billToLocation?: string;
}
