/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionTrackingDataSellerDataOnlineData { 
    /**
     * Hex, ref Companies.
     */
    readonly sellingCompany?: string;
    /**
     * Hex, ref Facilities.
     */
    readonly shipFrom?: string;
    /**
     * Hex, ref Users.
     */
    designatedSeller?: string;
}
