/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.247.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionChangePending } from './transactionChangePending';
import { TransactionCostDataPublic } from './transactionCostDataPublic';
import { TransactionMilestone } from './transactionMilestone';
import { TransactionRegister } from './transactionRegister';
import { TransactionTally } from './transactionTally';
import { TransactionTrackingData } from './transactionTrackingData';


export interface TransactionBase { 
    readonly id?: string;
    state?: TransactionBase.StateEnum;
    costData?: TransactionCostDataPublic;
    tally?: TransactionTally;
    trackingData?: TransactionTrackingData;
    transactionalJournalAllRead?: Array<string>;
    milestones?: Array<TransactionMilestone>;
    register?: TransactionRegister;
    changePending?: TransactionChangePending;
    readonly updatedAt?: Date;
    readonly createdAt?: Date;
}
export namespace TransactionBase {
    export type StateEnum = 'DRAFT' | 'QUOTE' | 'REVIEW' | 'CONFIRMED' | 'IN_TRANSIT' | 'COMPLETE' | 'CHANGE_PENDING' | 'CANCELED';
    export const StateEnum = {
        DRAFT: 'DRAFT' as StateEnum,
        QUOTE: 'QUOTE' as StateEnum,
        REVIEW: 'REVIEW' as StateEnum,
        CONFIRMED: 'CONFIRMED' as StateEnum,
        INTRANSIT: 'IN_TRANSIT' as StateEnum,
        COMPLETE: 'COMPLETE' as StateEnum,
        CHANGEPENDING: 'CHANGE_PENDING' as StateEnum,
        CANCELED: 'CANCELED' as StateEnum
    };
}
