/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransportMethodEmbeddedInTrackingData } from './transportMethodEmbeddedInTrackingData';


export interface TransactionTrackingDataTransportMethodUpdatePayload { 
    type: TransactionTrackingDataTransportMethodUpdatePayload.TypeEnum;
    carrier?: string;
    railRestriction?: TransactionTrackingDataTransportMethodUpdatePayload.RailRestrictionEnum;
    railCarNumber?: string;
    notes?: string;
    cost?: number;
}
export namespace TransactionTrackingDataTransportMethodUpdatePayload {
    export type TypeEnum = 'RAIL' | 'TRUCK' | 'HEAVY_TRUCK' | 'SHIP_FREE_ON_BOARD' | 'SHIP_CARGO';
    export const TypeEnum = {
        RAIL: 'RAIL' as TypeEnum,
        TRUCK: 'TRUCK' as TypeEnum,
        HEAVYTRUCK: 'HEAVY_TRUCK' as TypeEnum,
        SHIPFREEONBOARD: 'SHIP_FREE_ON_BOARD' as TypeEnum,
        SHIPCARGO: 'SHIP_CARGO' as TypeEnum
    };
    export type RailRestrictionEnum = 'OPEN' | 'CLOSED';
    export const RailRestrictionEnum = {
        OPEN: 'OPEN' as RailRestrictionEnum,
        CLOSED: 'CLOSED' as RailRestrictionEnum
    };
}
