/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionCreatePayload { 
    role: TransactionCreatePayload.RoleEnum;
}
export namespace TransactionCreatePayload {
    export type RoleEnum = 'BUYER' | 'SELLER';
    export const RoleEnum = {
        BUYER: 'BUYER' as RoleEnum,
        SELLER: 'SELLER' as RoleEnum
    };
}
