/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionChangePendingTransportCrmData { 
    /**
     * Hex, ref Crm-Contacts.
     */
    shipToContact?: string;
    /**
     * Hex, ref Crm-Locations.
     */
    shipToLocation?: string;
    /**
     * Hex, ref Crm-Contacts.
     */
    billToContact?: string;
    /**
     * Hex, ref Crm-Locations.
     */
    billToLocation?: string;
}
