/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface TransactionTrackingDataBuyerDataOnlineData { 
    /**
     * Hex, ref Companies.
     */
    readonly buyingCompany?: string;
    /**
     * Hex, ref Users.
     */
    buyingUser?: string;
    /**
     * Hex, ref Facilities.
     */
    shipTo?: string;
    /**
     * Hex, ref Users.
     */
    billToContact?: string;
    /**
     * Hex, ref Facilities.
     */
    billToLocation?: string;
}
