/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionTallyUnit } from './transactionTallyUnit';


export interface TransactionTally { 
    /**
     * Null is allowed.
     */
    contentDescription?: string;
    readonly units?: Array<TransactionTallyUnit>;
}
