/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TransactionCostDataCostOfGood } from './transactionCostDataCostOfGood';
import { TransactionTallyUnitPopulated } from './transactionTallyUnitPopulated';


export interface TransactionCostData { 
    shippingCost?: number;
    soldTally?: Array<TransactionTallyUnitPopulated>;
    cogs?: Array<TransactionCostDataCostOfGood>;
    cogp?: Array<TransactionCostDataCostOfGood>;
}
