/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesORDER { 
    ADD_ORDER?: string;
    GET_ORDER?: string;
    DELETE_ORDER?: string;
    ADD_ORDER_STOCK_DATA_TRANSACTION?: string;
    DELETE_ORDER_STOCK_DATA_TRANSACTION?: string;
}
