/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesRATETABLE { 
    ADD_RATE_TABLE?: string;
    UPDATE_RATE_TABLE?: string;
    DELETE_RATE_TABLE?: string;
    ADD_RATE_TABLE_CLONE?: string;
    ADD_RATE_TABLE_ENTRY?: string;
    ADD_RATE_TABLE_ENTRIES?: string;
    UPDATE_RATE_TABLE_ENTRY?: string;
    DELETE_RATE_TABLE_ENTRY?: string;
}
