/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesPURCHASEORDER {
    LIST_PURCHASE_ORDERS?: string;
    ADD_PURCHASE_ORDER?: string;
    GET_PURCHASE_ORDER?: string;
    UPDATE_PURCHASE_ORDER?: string;
    CLOSE_PURCHASE_ORDER?: string;
    DELETE_PURCHASE_ORDER?: string;
    ADD_PURCHASE_ORDER_OPEN_LINE_ITEM?: string;
    GET_PURCHASE_ORDER_OPEN_LINE_ITEM?: string;
    UPDATE_PURCHASE_ORDER_OPEN_LINE_ITEM?: string;
    DELETE_PURCHASE_ORDER_OPEN_LINE_ITEM?: string;
}
