/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { UserAccessControlRolesACCOUNT } from './userAccessControlRolesACCOUNT';
import { UserAccessControlRolesBILL } from './userAccessControlRolesBILL';
import { UserAccessControlRolesCOMPANY } from './userAccessControlRolesCOMPANY';
import { UserAccessControlRolesCRMACCOUNT } from './userAccessControlRolesCRMACCOUNT';
import { UserAccessControlRolesDIMENSION } from './userAccessControlRolesDIMENSION';
import { UserAccessControlRolesFACILITY } from './userAccessControlRolesFACILITY';
import { UserAccessControlRolesGROUP } from './userAccessControlRolesGROUP';
import { UserAccessControlRolesINVOICE } from './userAccessControlRolesINVOICE';
import { UserAccessControlRolesJOURNALENTRY } from './userAccessControlRolesJOURNALENTRY';
import { UserAccessControlRolesLABEL } from './userAccessControlRolesLABEL';
import { UserAccessControlRolesORDER } from './userAccessControlRolesORDER';
import { UserAccessControlRolesPRODUCT } from './userAccessControlRolesPRODUCT';
import { UserAccessControlRolesPURCHASEORDER } from './userAccessControlRolesPURCHASEORDER';
import { UserAccessControlRolesRATETABLE } from './userAccessControlRolesRATETABLE';
import { UserAccessControlRolesSALESORDER } from './userAccessControlRolesSALESORDER';
import { UserAccessControlRolesTRANSACTION } from './userAccessControlRolesTRANSACTION';


export interface UserAccessControlRoles {
    ACCOUNT?: UserAccessControlRolesACCOUNT;
    BILL?: UserAccessControlRolesBILL;
    COMPANY?: UserAccessControlRolesCOMPANY;
    CRM_ACCOUNT?: UserAccessControlRolesCRMACCOUNT;
    DIMENSION?: UserAccessControlRolesDIMENSION;
    FACILITY?: UserAccessControlRolesFACILITY;
    GROUP?: UserAccessControlRolesGROUP;
    INVOICE?: UserAccessControlRolesINVOICE;
    JOURNAL_ENTRY?: UserAccessControlRolesJOURNALENTRY;
    LABEL?: UserAccessControlRolesLABEL;
    ORDER?: UserAccessControlRolesORDER;
    PRODUCT?: UserAccessControlRolesPRODUCT;
    RATE_TABLE?: UserAccessControlRolesRATETABLE;
    SALES_ORDER?: UserAccessControlRolesSALESORDER;
    PURCHASE_ORDER?: UserAccessControlRolesPURCHASEORDER;
    TRANSACTION?: UserAccessControlRolesTRANSACTION;
}
