/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface User { 
    readonly id?: string;
    readonly username?: string;
    /**
     * Null is allowed.
     */
    firstName?: string;
    /**
     * Null is allowed.
     */
    lastName?: string;
    /**
     * Null is allowed.
     */
    profilePictureUrl?: string;
    productsOfInterestIds?: Array<string>;
    /**
     * Null is allowed.
     */
    title?: string;
    /**
     * Calling code. Null is allowed.
     */
    callingCode?: string;
    /**
     * Null is allowed.
     */
    workPhone?: string;
    readonly systemRoles?: Array<User.SystemRolesEnum>;
    readonly accountState?: User.AccountStateEnum;
    readonly group?: string;
    permissions?: any;
    preferences?: any;
    privacySettings?: any;
    readonly profileCompletionState?: User.ProfileCompletionStateEnum;
    accessControlRoles?: any;
    /**
     * Hex, ref Companies.
     */
    readonly companyId?: string;
    /**
     * Hex, ref Temporary-Companies.
     */
    readonly temporaryCompanyId?: string;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly createdAt?: Date;
    /**
     * The date-time notation as defined by RFC 3339, section 5.6.
     */
    readonly updatedAt?: Date;
}
export namespace User {
    export type SystemRolesEnum = 'COMPANY_ADMIN' | 'BILLING_ADMIN' | 'ANALYTIC_TEST_USER';
    export const SystemRolesEnum = {
        COMPANYADMIN: 'COMPANY_ADMIN' as SystemRolesEnum,
        BILLINGADMIN: 'BILLING_ADMIN' as SystemRolesEnum,
        ANALYTICTESTUSER: 'ANALYTIC_TEST_USER' as SystemRolesEnum
    };
    export type AccountStateEnum = 'NOT_ACTIVE' | 'WAIT_APPROVAL' | 'APPROVED' | 'HOLD' | 'UPDATE_REQUIRED';
    export const AccountStateEnum = {
        NOTACTIVE: 'NOT_ACTIVE' as AccountStateEnum,
        WAITAPPROVAL: 'WAIT_APPROVAL' as AccountStateEnum,
        APPROVED: 'APPROVED' as AccountStateEnum,
        HOLD: 'HOLD' as AccountStateEnum,
        UPDATEREQUIRED: 'UPDATE_REQUIRED' as AccountStateEnum
    };
    export type ProfileCompletionStateEnum = 'INITIAL' | 'PENDING_COMPANY' | 'MEMBER' | 'PROFILE' | 'COMPLETE';
    export const ProfileCompletionStateEnum = {
        INITIAL: 'INITIAL' as ProfileCompletionStateEnum,
        PENDINGCOMPANY: 'PENDING_COMPANY' as ProfileCompletionStateEnum,
        MEMBER: 'MEMBER' as ProfileCompletionStateEnum,
        PROFILE: 'PROFILE' as ProfileCompletionStateEnum,
        COMPLETE: 'COMPLETE' as ProfileCompletionStateEnum
    };
}
