/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.270.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesPRODUCTLOT { 
    ADD_PRODUCT_LOT?: string;
    GET_PRODUCT_LOT?: string;
    UPDATE_PRODUCT_LOT?: string;
    DELETE_PRODUCT_LOT?: string;
    LIST_PRODUCT_LOT_PRODUCTS?: string;
    ADD_PRODUCT_LOT_PRODUCT?: string;
    MOVE_PRODUCT_LOT_PRODUCT?: string;
}
