/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesFACILITY { 
    LIST_FACILITIES?: string;
    ADD_FACILITY?: string;
    GET_FACILITY?: string;
    UPDATE_FACILITY?: string;
    ADD_FACILITY_PERSONNEL?: string;
    DELETE_FACILITY_PERSONNEL?: string;
    ADD_FACILITY_TRANSPORT_METHOD?: string;
    DELETE_FACILITY_TRANSPORT_METHOD?: string;
}
