/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesINVOICE { 
    LIST_INVOICES?: string;
    ADD_INVOICE?: string;
    GET_INVOICE?: string;
    UPDATE_INVOICE?: string;
    UPDATE_INVOICE_STATE_REVIEW?: string;
    DELETE_INVOICE?: string;
    ADD_INVOICE_LINE_ITEM?: string;
    GET_INVOICE_LINE_ITEM?: string;
    UPDATE_INVOICE_LINE_ITEM?: string;
    DELETE_INVOICE_LINE_ITEM?: string;
    ADD_INVOICE_PAYMENT?: string;
    GET_INVOICE_PAYMENT?: string;
    UPDATE_INVOICE_PAYMENT?: string;
    DELETE_INVOICE_PAYMENT?: string;
}
