/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserUpdatePayload { 
    firstName: string;
    lastName: string;
    profilePictureUrl?: string;
    productsOfInterestIds: Array<string>;
    title: string;
    /**
     * Calling code.
     */
    callingCode: string;
    workPhone: string;
}
