/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesBILL {
    LIST_BILLS?: string;
    ADD_BILL?: string;
    GET_BILL?: string;
    UPDATE_BILL?: string;
    DELETE_BILL?: string;
    ADD_BILL_LINE_ITEM?: string;
    GET_BILL_LINE_ITEM?: string;
    UPDATE_BILL_LINE_ITEM?: string;
    DELETE_BILL_LINE_ITEM?: string;
    ADD_BILL_PAYMENT?: string;
    GET_BILL_PAYMENT?: string;
    UPDATE_BILL_PAYMENT?: string;
    DELETE_BILL_PAYMENT?: string;
}
