/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesCOMPANY { 
    GET_COMPANY?: string;
    UPDATE_COMPANY?: string;
    UPDATE_COMPANY_ACCOUNTING_PRACTICES?: string;
    UPDATE_COMPANY_ACCOUNTING_PRACTICES_DEFAULT_ACCOUNTS?: string;
    UPDATE_COMPANY_PRIVACY_SETTINGS?: string;
    UPDATE_COMPANY_SALES_PRACTICES?: string;
    LIST_COMPANY_PENDING_MEMBERS?: string;
    ADD_COMPANY_PENDING_MEMBER_ACTIVATION?: string;
    LIST_COMPANY_MEMBERS?: string;
    GET_COMPANY_MEMBER?: string;
    UPDATE_COMPANY_MEMBER?: string;
    UPDATE_COMPANY_MEMBER_ACCOUNT_STATE?: string;
    UPDATE_COMPANY_MEMBER_ACCESS_CONTROL_ROLES?: string;
    UPDATE_COMPANY_MEMBER_GROUP?: string;
    UPDATE_COMPANY_MEMBER_PRIVACY_SETTINGS?: string;
}
