/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesSALESORDER { 
    LIST_SALES_ORDERS?: string;
    ADD_SALES_ORDER?: string;
    GET_SALES_ORDER?: string;
    UPDATE_SALES_ORDER?: string;
    CLOSE_SALES_ORDER?: string;
    DELETE_SALES_ORDER?: string;
    ADD_SALES_ORDER_OPEN_LINE_ITEM?: string;
    GET_SALES_ORDER_OPEN_LINE_ITEM?: string;
    UPDATE_SALES_ORDER_OPEN_LINE_ITEM?: string;
    DELETE_SALES_ORDER_OPEN_LINE_ITEM?: string;
}
