/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesCRMACCOUNT { 
    LIST_CRM_ACCOUNTS?: string;
    ADD_CRM_ACCOUNT?: string;
    UPDATE_CRM_ACCOUNT?: string;
    GET_CRM_ACCOUNT_SALES_INFO?: string;
    UPDATE_CRM_ACCOUNT_SALES_INFO?: string;
    GET_CRM_ACCOUNT_CREDIT_INFO?: string;
    UPDATE_CRM_ACCOUNT_CREDIT_INFO?: string;
    GET_CRM_ACCOUNT_PAYMENT_INFO?: string;
    UPDATE_CRM_ACCOUNT_PAYMENT_INFO?: string;
    UPDATE_CRM_ACCOUNT_LABELS?: string;
    LIST_CRM_CONTACTS?: string;
    ADD_CRM_ACCOUNT_CONTACT?: string;
    UPDATE_CRM_ACCOUNT_CONTACT?: string;
    GET_CRM_ACCOUNT_CONTACT_SALES_INFO?: string;
    UPDATE_CRM_ACCOUNT_CONTACT_SALES_INFO?: string;
    UPDATE_CRM_ACCOUNT_CONTACT_LABELS?: string;
    LIST_CRM_LOCATIONS?: string;
    ADD_CRM_ACCOUNT_LOCATION?: string;
    UPDATE_CRM_ACCOUNT_LOCATION?: string;
    GET_CRM_ACCOUNT_LOCATION_SALES_INFO?: string;
    UPDATE_CRM_ACCOUNT_LOCATION_SALES_INFO?: string;
    UPDATE_CRM_ACCOUNT_LOCATION_LABELS?: string;
}
