/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesPRODUCT { 
    SEARCH_PRODUCTS?: string;
    ADD_PRODUCTS?: string;
    UPDATE_PRODUCTS_OWNER?: string;
    UPDATE_PRODUCTS_PERMISSION?: string;
    UPDATE_PRODUCTS_SALES_NOTES?: string;
    UPDATE_PRODUCTS_SALES_DATA_PRICE_OF_MERIT?: string;
    UPDATE_PRODUCTS_SALES_DATA_SHIP_WEEK_ESTIMATE?: string;
    UPDATE_PRODUCT_LOT?: string;
    UPDATE_PRODUCT_CONTRACT?: string;
    UPDATE_PRODUCT_SPEC_LENGTH_UNITS?: string;
}
