/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.316.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesJOURNALENTRY { 
    SEARCH_JOURNAL_ENTRIES?: string;
    ADD_JOURNAL_ENTRY?: string;
    GET_JOURNAL_ENTRY?: string;
    UPDATE_JOURNAL_ENTRY?: string;
    UPDATE_JOURNAL_ENTRY_STATE?: string;
    DELETE_JOURNAL_ENTRY?: string;
}
