/**
 * Base API
 * Base API Definition.
 *
 * OpenAPI spec version: 0.278.0
 * Contact: hambardzumyan.albert@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UserAccessControlRolesCOSTCENTER { 
    LIST_COST_CENTERS?: string;
    ADD_COST_CENTER?: string;
    UPDATE_COST_CENTER?: string;
    DELETE_COST_CENTER?: string;
}
